# Generated by Django 5.2.1 on 2025-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_books_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
