# Generated by Django 5.2.1 on 2025-06-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_books_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
